config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts
  root to: 'pages#home'

  get 'pages/about'

  get 'pages/faq'

  get 'pages/mydash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body

    belongs_to :user 

    scope :posts_by, ->(user) { where(user_id: user.id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  
  def first_name
    self.name.split.first 
  end
  def last_name
    self.name.split.last 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end
    

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.last(3)
  end

  def about
  end

  def faq
  end

  def mydash
    @posts = Post.posts_by(current_user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :thumb_image, :main_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def image_generator(height:, width:)
        "http://via.placeholder.com/#{height}x#{width}"
    end

    def post_img img, type
        if img.model.main_image? || img.model.thumb_image?
            img
        elsif type == 'thumb'
            image_generator(height: '350', width: '200')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<div class="home">
    <div class="row">
        <div class="col-md-6">
            <div class="jumbotron jumbotron-fluid">
                <div class="container justify-content-center">
                    <h1 class="display-4">
                        <% if current_user %>
                            Welcome, <%= current_user.first_name %>
                        <% else %>
                            Welcome!
                        <% end %>
                    </h1>
                    <p class="lead">Some more welcoming content here</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <header class="text-center">
                <h2>Recent Posts</h2>
            </header>
            <% @posts.each do |post| %>
                <div class="card" style="margin: 15px;">
                    <div class="row">
                        <div class="col-md-8" style="padding: 10px;">
                            <%= image_tag post.thumb_image, width: '60%' %>
                        </div>
                        <div class="col-md-4" style="margin-top: 10%;">
                            <h3><%= link_to post.title, post_path(post) %></h3>
                            <p><small>Last updated <%= distance_of_time_in_words(post.updated_at, Time.now)%> ago</small></p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/mydash.html.erb
<div class="container">
    <% @posts.each do |post| %>
        <div class="row">
            <div class="col-lg-8">
                <%= link_to post_path(post) do %>
                    <div class="card" style="margin: 25px; padding: 15px;">
                        <p><%= post.title %></p>
                        <p><%= post.user.name %>
                    </div>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :post_title, class: "form-control", style: "margin-bottom: 55px;" %>
      </div>

      <div class="form-group">
        <label class="btn btn-secondary">
          Upload thumb image 
          <%= form.file_field :thumb_image, id: :post_thumb_image, style: 'display: none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-secondary">
          Upload main image 
          <%= form.file_field :main_image, id: :post_main_image, style: 'display: none;' %>
        </label>
      </div>
    </div>
    <div class="col-md-6" style="margin-bottom: 55px;">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, id: :post_body, class: "form-control", rows: 15 %>
      </div>
    </div>
  </div>

  <hr />

  <div class="form-group" style="margin-top: 65px;">
    <%= form.submit "Save Post", class: 'btn btn-secondary btn-block' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h1>Posts</h1>
      <hr />
      <% @posts.each do |post| %>
        <div class="card" style="margin: 25px; padding: 10px;">
          <%= image_tag post.thumb_image, style: "width: auto;" %>
          <h3><%= link_to post.title, post_path(post) %></h3>
        </div>
      <% end %>
    </div>

    <div class="col-md-2">
      <div>
        <h2>Options</h2>
      </div>
    </div>
  </div>
</div>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <strong><%= @post.title %></strong>
      <hr />
      <%# <%= image_tag post_img(@post.main_image, 'main'), width: '100%' %> %>
    </div>
    <div class="col-lg-4" style='margin-top: 10%; padding: 25px;'>
      <%= @post.body %>
    </div>
  </div>
</div>

<div style="position: fixed; bottom: 0;">
  <% if current_user %>
    <% if current_user.id == @post.user_id %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-light' %> |
    <% end %>
  <% end %>
  <%= link_to 'Back', posts_path, class: 'btn btn-light' %>
</div>

app/views/shared/_nav.html.erb
<div>
    <ul class="nav justify-content-end">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to "About", pages_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to "FAQ's", pages_faq_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to "Posts", posts_path, class: 'nav-link' %>
        </li>
        
        <% if current_user %>
            <li class="nav-item">
                <%= link_to "New Post", new_post_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "My Dash", pages_mydash_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Edit Registration", edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
</div>